name: CI Checks

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'  # タグのプッシュ時はリリースワークフローが実行されるため除外

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Firefox dependencies
        run: pnpm install:firefox-deps

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Package extensions
        run: pnpm package

      - name: Verify package artifacts
        run: |
          echo "Checking package artifacts..."
          ls -la ./dist || echo "No dist directory found"
          ls -la ./dist/chrome-ext || echo "No chrome-ext directory found"
          ls -la ./dist/firefox-addon || echo "No firefox-addon directory found"
          if [ ! -d "./dist" ] || [ ! -d "./dist/chrome-ext" ] || [ ! -d "./dist/firefox-addon" ]; then
            echo "Package artifacts are missing!"
            exit 1
          fi
          if [ ! -f "./dist/chrome-ext/music-x1-chrome-v"*.zip ] || [ ! -f "./dist/firefox-addon/music-x1-firefox-v"*.xpi ]; then
            echo "ZIP/XPI packages are missing!"
            exit 1
          fi
          echo "Package verification completed successfully."