name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18
          pnpm-version: 9
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm run build
          if [ ! -d "dist" ]; then
            echo "dist directory was not created"
            exit 1
          fi

      - name: Create ZIP files
        run: |
          # Create extension zip
          cd dist
          zip -r ../music-x1-${{ github.ref_name }}.zip .
          cd ..
          
          # Create source code zip
          git archive -o music-x1-source-${{ github.ref_name }}.zip HEAD

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            music-x1-${{ github.ref_name }}.zip
            music-x1-source-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
